version: 2.1
jobs:
  fedora:
    docker:
      - image: fedora
    steps:
      - checkout
      - run:
         command: ./tests/ci_test.sh
         no_output_timeout: 20m
workflows:
  version: 2
  workflow:
    jobs:
    - fedora
